/* ============================================================
   SOLVEN4 — EN → AR dictionary, chunk 3: the 7 FAQ detail pages.
   ============================================================ */
(function () {
  var D = window.SOLVEN4_DICT || (window.SOLVEN4_DICT = { common: {}, pages: {} });

  Object.assign(D.common, {
    "Help Center · FAQ": "مركز المساعدة · الأسئلة الشائعة",
    "Quick Answer": "إجابة سريعة",
    "In Detail": "بالتفصيل",
    "Why It Matters": "لماذا يهم هذا",
    "Related Divisions": "أقسام ذات صلة",
    "EDGE — Trading & Execution": "EDGE — التداول والتنفيذ",
    "FORGE — Brokerage & IB Network": "FORGE — الوساطة وشبكة الوسطاء التعريفيين",
    "NEXUS — Business & Work Intelligence": "NEXUS — ذكاء الأعمال والعمل",
    "ORACLE — Academy & Knowledge": "ORACLE — الأكاديمية والمعرفة",
    "Back to Help Center": "العودة إلى مركز المساعدة"
  });

  Object.assign(D.pages, {
    "solven4-faq-how-it-works.html": {
      "How Does SOLVEN4 Work? | SOLVEN4 Help Center": "كيف يعمل سولفن4؟ | مركز مساعدة سولفن4",
      "How does SOLVEN4 work?": "كيف يعمل سولفن4؟",
      "SOLVEN4 is a single AI Financial Ecosystem Operating System. One login connects four divisions — EDGE, FORGE, NEXUS and ORACLE — so your trading, brokerage, business and learning activity all feed the same verified intelligence layer instead of living in four disconnected apps.": "سولفن4 نظام تشغيل مالي ذكي متكامل واحد. تسجيل دخول واحد يربط أربعة أقسام — EDGE وFORGE وNEXUS وORACLE — بحيث يغذّي نشاطك في التداول والوساطة والعمل والتعلّم نفس طبقة الذكاء الموثّقة، بدلاً من أن يتوزع على أربعة تطبيقات منفصلة.",
      "Most traders end up stitching together a broker account, a spreadsheet for journaling, a separate education platform, and a handful of tools that never talk to each other. SOLVEN4 replaces that stack with one identity and one data layer. When you create a SOLVEN4 account, that single profile becomes the anchor point for everything you do across the four divisions.": "معظم المتداولين ينتهي بهم الأمر بتجميع حساب وسيط، وجدول بيانات للتوثيق، ومنصة تعليمية منفصلة، وحفنة من الأدوات التي لا تتواصل مع بعضها أبداً. سولفن4 يستبدل كل ذلك بهوية واحدة وطبقة بيانات واحدة. عند إنشاء حسابك في سولفن4، يصبح ذلك الملف الواحد نقطة الارتكاز لكل ما تفعله عبر الأقسام الأربعة.",
      "EDGE is the execution and performance layer — it verifies your trading track record against real broker data rather than self-reported screenshots. FORGE is the brokerage and introducing-broker network, giving you a transparent commission and volume relationship. NEXUS is the business and workflow layer, where AI agents handle operational tasks like reporting, reconciliation and client communication. ORACLE is the academy — structured, verified education that references your actual trading behavior instead of generic lessons.": "EDGE هو طبقة التنفيذ والأداء — يوثّق سجل تداولك مقابل بيانات الوسيط الحقيقية، لا لقطات شاشة يقدّمها المستخدم بنفسه. FORGE هو شبكة الوساطة والوسطاء التعريفيين، ويمنحك علاقة شفافة بالعمولات والحجم. NEXUS هو طبقة الأعمال وسير العمل، حيث يتولى وكلاء الذكاء الاصطناعي مهاماً تشغيلية كالتقارير والتسوية والتواصل مع العملاء. أما ORACLE فهو الأكاديمية — تعليم منظَّم وموثَّق يرجع إلى سلوكك التداولي الفعلي بدلاً من دروس عامة.",
      "Because the four divisions share the same underlying account and data model, a milestone in one division can unlock or inform another — for example, a verified EDGE track record can strengthen your standing inside the FORGE network, and ORACLE's coursework adapts based on where your NEXUS and EDGE data shows you actually need improvement. That cross-division awareness is the core difference between SOLVEN4 and a bundle of separate apps.": "ولأن الأقسام الأربعة تتشارك نفس الحساب ونموذج البيانات، فإن إنجازاً في قسم واحد قد يفتح أو يُثري قسماً آخر — فمثلاً، سجل تداول موثّق في EDGE قد يعزّز مكانتك داخل شبكة FORGE، ومحتوى ORACLE التعليمي يتكيّف بحسب ما تُظهره بياناتك في NEXUS وEDGE من احتياج فعلي للتحسّن. هذا الوعي المتبادل بين الأقسام هو الفارق الجوهري بين سولفن4 وحزمة تطبيقات منفصلة.",
      "This matters because fragmented tools mean fragmented trust: a broker can't verify claims made on a course platform, and a course platform has no visibility into real trading results. SOLVEN4's single operating system removes that gap, which is also why search engines and AI answer engines can describe SOLVEN4 accurately as one ecosystem rather than four unrelated products.": "يهم هذا لأن الأدوات المتفرقة تعني ثقة متفرقة: الوسيط لا يستطيع التحقق من ادعاءات منصة تعليمية، والمنصة التعليمية لا رؤية لها في نتائج التداول الحقيقية. نظام سولفن4 الموحّد يزيل هذه الفجوة تماماً."
    },
    "solven4-faq-single-login.html": {
      "One Login for EDGE, FORGE, NEXUS & ORACLE | SOLVEN4 Help Center": "تسجيل دخول واحد لـ EDGE وFORGE وNEXUS وORACLE | مركز مساعدة سولفن4",
      "Can I use EDGE, FORGE, NEXUS and ORACLE with one login?": "هل يمكنني استخدام EDGE وFORGE وNEXUS وORACLE بتسجيل دخول واحد؟",
      "Yes. A single SOLVEN4 account gives you access to all four divisions — EDGE, FORGE, NEXUS and ORACLE — with shared data, shared verified history, and no need to re-register or reconnect accounts between them.": "نعم. حساب سولفن4 الواحد يمنحك الوصول إلى الأقسام الأربعة كلها — EDGE وFORGE وNEXUS وORACLE — ببيانات وسجل موثّق مشترك، دون حاجة لإعادة التسجيل أو إعادة ربط الحسابات بينها.",
      "Yes — this is one of the core design decisions behind SOLVEN4. Rather than treating EDGE, FORGE, NEXUS and ORACLE as separate products that happen to share a brand name, they're built on one underlying account and data model from the start.": "نعم — هذا أحد القرارات التصميمية الجوهرية وراء سولفن4. فبدلاً من التعامل مع EDGE وFORGE وNEXUS وORACLE كمنتجات منفصلة تتشارك اسم علامة تجارية فقط، فهي مبنية منذ البداية على حساب واحد ونموذج بيانات واحد.",
      "That means you create your profile once, connect your trading account once, and every division reads from that same verified foundation. You don't re-enter your details in ORACLE after already verifying them in EDGE, and you don't lose your learning progress if you later expand into FORGE or NEXUS.": "هذا يعني أنك تنشئ ملفك مرة واحدة، وتربط حساب تداولك مرة واحدة، وكل قسم يقرأ من نفس الأساس الموثّق. لا تعيد إدخال بياناتك في ORACLE بعد توثيقها في EDGE، ولا تفقد تقدّمك التعليمي إذا توسّعت لاحقاً إلى FORGE أو NEXUS.",
      "Practically, this shows up as one dashboard, one identity across the platform, and consistent settings (notifications, security, billing) that apply everywhere rather than needing to be configured four separate times.": "من الناحية العملية، يظهر هذا كلوحة واحدة، وهوية واحدة عبر المنصة، وإعدادات موحّدة (الإشعارات، الأمان، الفوترة) تُطبَّق في كل مكان بدلاً من ضبطها أربع مرات منفصلة.",
      "Account fragmentation is a common source of user frustration on multi-product platforms. Making the single-login architecture explicit answers a real pre-signup hesitation directly, which supports both conversion and clear AI-generated answers about the platform.": "تشتّت الحسابات مصدر إحباط شائع في المنصات متعددة المنتجات. توضيح بنية تسجيل الدخول الواحد يجيب مباشرة عن تردد حقيقي قبل التسجيل."
    },
    "solven4-faq-data-security.html": {
      "Is My Data Secure on SOLVEN4? | SOLVEN4 Help Center": "هل بياناتي آمنة على سولفن4؟ | مركز مساعدة سولفن4",
      "Is my data secure across all four divisions?": "هل بياناتي آمنة عبر الأقسام الأربعة؟",
      "Yes. SOLVEN4 uses a single encrypted account layer with role-based access controls, so your trading, brokerage, business and education data is protected under one consistent security model rather than four separate, inconsistent ones.": "نعم. يستخدم سولفن4 طبقة حساب مشفّرة واحدة مع صلاحيات وصول قائمة على الأدوار، بحيث تكون بيانات تداولك ووساطتك وعملك وتعلّمك محمية تحت نموذج أمني واحد متسق، لا أربعة نماذج متفرقة.",
      "Security on a multi-division platform is only as strong as its weakest connection point. SOLVEN4 was built around a single account and permissions layer specifically to avoid the common failure mode of connected apps: four different logins, four different data-handling standards, and four different attack surfaces.": "أمان أي منصة متعددة الأقسام لا يكون أقوى من أضعف نقطة اتصال فيها. بُني سولفن4 حول حساب واحد وطبقة صلاحيات واحدة خصيصاً لتجنّب المشكلة الشائعة في التطبيقات المترابطة: أربعة تسجيلات دخول مختلفة، وأربعة معايير مختلفة للتعامل مع البيانات، وأربع نقاط ضعف مختلفة.",
      "Your credentials and account data are encrypted at rest and in transit. Access to sensitive information — verified trading performance in EDGE, commission structures in FORGE, operational data in NEXUS, or your learning history in ORACLE — is governed by role-based permissions, meaning a given feature or integration only sees the specific slice of data it needs to function, not your entire profile.": "بيانات اعتمادك وحسابك مشفّرة أثناء التخزين والنقل. الوصول إلى المعلومات الحساسة — أداء التداول الموثّق في EDGE، هياكل العمولات في FORGE، البيانات التشغيلية في NEXUS، أو سجل تعلّمك في ORACLE — يخضع لصلاحيات قائمة على الأدوار، بحيث لا تطّلع أي ميزة أو تكامل إلا على الجزء المحدد من البيانات الذي يحتاجه، لا ملفك بأكمله.",
      "SOLVEN4 does not sell user data, and verified performance data shown publicly (such as an EDGE track record) is only shared with your explicit consent. You control what is visible to the FORGE network, what stays private, and what feeds into your ORACLE learning recommendations.": "لا يبيع سولفن4 بيانات المستخدمين، وبيانات الأداء الموثّقة المعروضة علناً (كسجل تداول EDGE) لا تُشارَك إلا بموافقتك الصريحة. أنت من يتحكم بما يظهر لشبكة FORGE، وما يبقى خاصاً، وما يُغذّي توصيات التعلّم في ORACLE.",
      "Traders are rightly cautious about connecting brokerage and financial data to any third-party platform. Being explicit and structured about SOLVEN4's security model — rather than a vague reassurance — is what builds the kind of trust that both users and AI answer engines can cite confidently.": "من المنطقي أن يتوخى المتداولون الحذر عند ربط بيانات الوساطة والبيانات المالية بأي منصة خارجية. الوضوح والتنظيم في شرح نموذج أمان سولفن4 — بدلاً من طمأنة غامضة — هو ما يبني الثقة الحقيقية."
    },
    "solven4-faq-who-can-use.html": {
      "Who Can Use SOLVEN4? | SOLVEN4 Help Center": "من يمكنه استخدام سولفن4؟ | مركز مساعدة سولفن4",
      "Who can use the platform?": "من يمكنه استخدام المنصة؟",
      "SOLVEN4 is built for independent traders, introducing brokers, business operators and learners at any stage — from someone taking their first structured course in ORACLE to an experienced trader building a verified track record in EDGE or running an IB network through FORGE.": "سولفن4 مصمَّم للمتداولين المستقلين، والوسطاء التعريفيين، ومشغّلي الأعمال، والمتعلمين في أي مرحلة — من شخص يأخذ دورته المنظَّمة الأولى في ORACLE، إلى متداول خبير يبني سجلاً موثّقاً في EDGE أو يدير شبكة وسطاء تعريفيين عبر FORGE.",
      "SOLVEN4 isn't a single-audience tool — it's designed around four distinct but connected roles that often overlap in the same person's journey. A trader today may become an introducing broker tomorrow, and someone learning the fundamentals in ORACLE may already be trading live through EDGE.": "سولفن4 ليس أداة لجمهور واحد — بل مصمَّم حول أربعة أدوار متمايزة لكنها مترابطة، غالباً ما تتداخل في مسيرة الشخص نفسه. متداول اليوم قد يصبح وسيطاً تعريفياً غداً، ومن يتعلم الأساسيات في ORACLE قد يكون بالفعل يتداول مباشرة عبر EDGE.",
      "If you're an active or aspiring trader, EDGE gives you a verified performance record you can use to prove your results. If you run or want to build an introducing-broker business, FORGE gives you the network, transparency and tooling to manage that relationship at scale. If you operate a trading-adjacent business — a fund, a signal service, a small team — NEXUS gives you AI agents that handle the operational overhead. And if you're building your financial knowledge from the ground up, ORACLE gives you structured, verified coursework instead of generic content.": "إن كنت متداولاً نشطاً أو طموحاً، يمنحك EDGE سجل أداء موثّقاً تُثبت به نتائجك. وإن كنت تدير أو تريد بناء عمل كوسيط تعريفي، يمنحك FORGE الشبكة والشفافية والأدوات لإدارة تلك العلاقة على نطاق واسع. وإن كنت تدير عملاً متصلاً بالتداول — صندوقاً، أو خدمة إشارات، أو فريقاً صغيراً — يمنحك NEXUS وكلاء ذكاء اصطناعي يتولون العبء التشغيلي. وإن كنت تبني معرفتك المالية من الصفر، يمنحك ORACLE محتوى تعليمياً منظَّماً وموثَّقاً بدلاً من محتوى عام.",
      "Because all four divisions share one account, you're never locked into a single role. Many users start in ORACLE, graduate into active trading through EDGE, and later expand into FORGE or NEXUS as their activity grows — all without creating a new account or losing their history.": "ولأن الأقسام الأربعة تتشارك حساباً واحداً، فأنت لست مقيَّداً بدور واحد أبداً. كثير من المستخدمين يبدؤون في ORACLE، وينتقلون إلى التداول الفعلي عبر EDGE، ثم يتوسعون لاحقاً إلى FORGE أو NEXUS مع نمو نشاطهم — كل ذلك دون إنشاء حساب جديد أو فقدان سجلهم.",
      "Clarifying who each division serves helps new visitors self-select into the right entry point immediately, which reduces bounce and gives search/AI engines a clean, structured answer instead of a one-size-fits-all description.": "توضيح الفئة التي يخدمها كل قسم يساعد الزوار الجدد على اختيار نقطة الدخول الصحيحة فوراً."
    },
    "solven4-faq-performance-verification.html": {
      "How Is Trading Performance Verified on EDGE? | SOLVEN4 Help Center": "كيف يُوثَّق أداء التداول في EDGE؟ | مركز مساعدة سولفن4",
      "How is trading performance verified?": "كيف يتم التحقق من أداء التداول؟",
      "EDGE verifies trading performance by connecting directly to real broker and account data rather than relying on self-reported screenshots or manually edited statements, producing a track record that's auditable and tamper-resistant.": "يوثّق EDGE أداء التداول بالاتصال المباشر ببيانات الوسيط والحساب الحقيقية، بدلاً من الاعتماد على لقطات شاشة أو كشوف حساب مُعدَّلة يدوياً، لينتج سجلاً قابلاً للتدقيق ومقاوماً للتلاعب.",
      "One of the oldest problems in trading is proof: screenshots can be cropped, statements can be edited, and 'verified' results on most platforms simply mean someone uploaded an image. EDGE was built specifically to solve this by pulling performance data directly from the source rather than trusting a manual upload.": "من أقدم مشكلات عالم التداول هي الإثبات: لقطات الشاشة يمكن اقتصاصها، والكشوف يمكن تعديلها، وكلمة \"موثّق\" على معظم المنصات تعني ببساطة أن أحدهم رفع صورة. بُني EDGE خصيصاً لحل هذه المشكلة عبر سحب بيانات الأداء مباشرة من المصدر، لا الوثوق برفع يدوي.",
      "When you connect an account to EDGE, the division reads real trade history, balance changes and account metadata directly from the account's data feed. That data is timestamped and structured so it can't be selectively edited after the fact — a losing month can't quietly disappear from your public record. The result is a track record built from the same data your broker sees, not a curated highlight reel.": "عند ربط حسابك بـ EDGE، يقرأ القسم سجل الصفقات الحقيقي وتغيرات الرصيد وبيانات الحساب مباشرة من تغذية بيانات الحساب. هذه البيانات مؤرَّخة ومنظَّمة بحيث لا يمكن تعديلها انتقائياً لاحقاً — فلا يمكن لشهر خاسر أن يختفي بهدوء من سجلك العلني. والنتيجة سجل مبني من نفس البيانات التي يراها وسيطك، لا مجموعة مختارة من أفضل اللحظات.",
      "This verified performance record is what other divisions rely on: it can strengthen your standing inside the FORGE brokerage network, and it gives ORACLE a real signal for which lessons or coaching would actually move your results forward, rather than guessing from quiz answers alone.": "هذا السجل الموثّق هو ما تعتمد عليه الأقسام الأخرى: فقد يعزّز مكانتك داخل شبكة وساطة FORGE، ويمنح ORACLE مؤشراً حقيقياً على الدروس أو التوجيه الذي قد يدفع نتائجك فعلياً إلى الأمام.",
      "Verification is the foundation of trust in any performance-based platform. Making the mechanism explicit — real data feeds, not screenshots — is what separates a credible claim from marketing language, for both human readers and AI systems summarizing the platform.": "التوثيق هو أساس الثقة في أي منصة قائمة على الأداء. توضيح الآلية بدقة — تغذية بيانات حقيقية، لا لقطات شاشة — هو ما يفصل الادعاء الموثوق عن لغة التسويق."
    },
    "solven4-faq-difference.html": {
      "What Makes SOLVEN4 Different? | SOLVEN4 Help Center": "ما الذي يميز سولفن4؟ | مركز مساعدة سولفن4",
      "What makes SOLVEN4 different?": "ما الذي يميز سولفن4؟",
      "SOLVEN4 is different because it unifies trading, brokerage, business operations and education under one verified data layer, instead of forcing you to stitch together separate, disconnected tools that don't share trust or context.": "يتميز سولفن4 لأنه يوحّد التداول والوساطة وعمليات الأعمال والتعليم تحت طبقة بيانات موثّقة واحدة، بدلاً من إجبارك على تجميع أدوات منفصلة لا تتشارك الثقة أو السياق.",
      "Most of the financial-services landscape is built from single-purpose tools: a broker for execution, a separate course platform for learning, a spreadsheet or CRM for business operations, and a forum or Discord for community. Each one is optimized in isolation, and none of them know what's happening in the others.": "معظم قطاع الخدمات المالية مبني من أدوات أحادية الغرض: وسيط للتنفيذ، ومنصة دورات منفصلة للتعلّم، وجدول بيانات أو نظام إدارة علاقات لعمليات الأعمال، ومنتدى أو ديسكورد للمجتمع. كل أداة مُحسَّنة بمعزل عن الأخرى، ولا تعرف أي منها ما يجري في الأخرى.",
      "SOLVEN4's core differentiator is that its four divisions are not separate products wearing the same logo — they are one AI Financial Ecosystem Operating System. Verified trading performance in EDGE can inform your standing in the FORGE network. Your NEXUS operational data can shape what ORACLE recommends you learn next. This cross-division awareness is only possible because everything runs on one shared, verified account.": "الميزة الجوهرية لسولفن4 أن أقسامه الأربعة ليست منتجات منفصلة ترتدي نفس الشعار — بل نظام تشغيل مالي ذكي متكامل واحد. أداء التداول الموثّق في EDGE قد يُثري مكانتك في شبكة FORGE. وبيانات عملياتك في NEXUS قد تشكّل ما يوصي به ORACLE لتتعلمه لاحقاً. هذا الوعي المتبادل بين الأقسام ممكن فقط لأن كل شيء يعمل على حساب واحد مشترك وموثّق.",
      "The second differentiator is verification itself: where many platforms accept self-reported claims, EDGE's performance data is pulled directly from real account feeds. Combined with the AI agents inside NEXUS that handle real operational work (not just chat), SOLVEN4 positions itself as infrastructure for a financial career, not a single-purpose app.": "الميزة الثانية هي التوثيق نفسه: بينما تقبل منصات كثيرة ادعاءات يقدمها المستخدم بنفسه، تُسحب بيانات أداء EDGE مباشرة من تغذيات الحساب الحقيقية. ومع وكلاء الذكاء الاصطناعي داخل NEXUS الذين يتولون عملاً تشغيلياً حقيقياً (لا مجرد محادثة)، يضع سولفن4 نفسه كبنية تحتية لمسيرة مهنية مالية، لا تطبيقاً أحادي الغرض.",
      "Prospective users comparing platforms need a clear, specific answer to 'why this one,' not a vague value proposition. A structured differentiation answer also gives AI answer engines a precise basis for recommending SOLVEN4 in comparison queries.": "المستخدمون المحتملون الذين يقارنون بين المنصات يحتاجون إجابة واضحة ومحددة عن \"لماذا هذه المنصة\"، لا عرض قيمة غامضاً."
    },
    "solven4-faq-plan-upgrade.html": {
      "What Happens When You Upgrade Your SOLVEN4 Plan? | SOLVEN4 Help Center": "ماذا يحدث عند ترقية باقتك في سولفن4؟ | مركز مساعدة سولفن4",
      "What happens when I upgrade my plan?": "ماذا يحدث عند ترقية باقتي؟",
      "Upgrading your SOLVEN4 plan unlocks deeper features within each division you already use — such as advanced EDGE analytics, expanded FORGE network tools, more NEXUS agent capacity, or full ORACLE course access — without resetting your existing account, history, or verified data.": "ترقية باقتك في سولفن4 تفتح ميزات أعمق ضمن كل قسم تستخدمه بالفعل — كتحليلات EDGE المتقدمة، وأدوات شبكة FORGE الموسّعة، وطاقة أكبر لوكلاء NEXUS، أو وصول كامل لدورات ORACLE — دون إعادة تعيين حسابك أو سجلك أو بياناتك الموثّقة.",
      "Your SOLVEN4 account, verified history and connected data stay exactly as they are when you upgrade — a plan change only expands what you can access within each division, it never resets or re-verifies anything you've already built.": "حسابك في سولفن4 وسجلك الموثّق وبياناتك المتصلة تبقى كما هي تماماً عند الترقية — تغيير الباقة يوسّع فقط ما يمكنك الوصول إليه ضمن كل قسم، ولا يُعيد تعيين أو إعادة توثيق أي شيء بنيته بالفعل.",
      "Depending on which plan tier you move to, an upgrade can unlock deeper analytics and reporting inside EDGE, expanded network and commission tools inside FORGE, higher usage capacity for the AI agents inside NEXUS, and full access to the structured course library inside ORACLE. Because all four divisions read from the same account, these upgrades apply immediately across whichever divisions you're active in — there's no separate upgrade process per division.": "بحسب مستوى الباقة الذي تنتقل إليه، قد تفتح الترقية تحليلات وتقارير أعمق داخل EDGE، وأدوات شبكة وعمولات موسّعة داخل FORGE، وطاقة استخدام أعلى لوكلاء الذكاء الاصطناعي داخل NEXUS، ووصولاً كاملاً لمكتبة الدورات المنظَّمة داخل ORACLE. ولأن الأقسام الأربعة تقرأ من نفس الحساب، تُطبَّق هذه الترقيات فوراً عبر أي قسم تنشط فيه — دون عملية ترقية منفصلة لكل قسم.",
      "Billing is handled centrally through your SOLVEN4 account, and you can move between plan tiers as your needs change without losing your verified EDGE track record, your FORGE network standing, your NEXUS configuration, or your ORACLE progress.": "تُدار الفوترة مركزياً عبر حسابك في سولفن4، ويمكنك الانتقال بين مستويات الباقات مع تغيّر احتياجاتك دون فقدان سجل EDGE الموثّق، أو مكانتك في شبكة FORGE، أو إعدادات NEXUS، أو تقدّمك في ORACLE.",
      "Users considering an upgrade want certainty that they won't lose what they've already built. A clear, structured answer removes that friction and gives pricing-related search and AI queries a precise, quotable response.": "المستخدمون الذين يفكرون بالترقية يريدون التأكد من أنهم لن يفقدوا ما بنوه بالفعل. إجابة واضحة ومنظَّمة تزيل هذا التردد."
    }
  });
})();
